# -----------------------------
# Connectivity & Resources
# -----------------------------
listen_addresses = '*'          # Required for Docker networking
# max_connections = 100           # Enough for 8 threads + PMM + overhead
# shared_buffers = 256MB          # 25% of 1GB RAM (standard dev target)
# work_mem = 16MB                 # Faster sorts/joins for 8 threads

# -----------------------------
# Extensions (The Performance "Eyes")
# -----------------------------
# Load both for maximum PMM query analytics
shared_preload_libraries = 'pg_stat_monitor,pg_stat_statements,pg_prewarm'

# -----------------------------
# Statistics & Monitoring
# -----------------------------
track_activities = on
track_counts = on
track_io_timing = on
track_functions = all

# pg_stat_monitor specific settings
pg_stat_monitor.pgsm_enable_query_plan = 1
pg_stat_monitor.pgsm_track_waiting_queries = 1
pg_stat_monitor.pgsm_bucket_time = 60   # 1-minute snapshots for PMM


# -----------------------------
# Write Ahead Log (WAL)
# -----------------------------
# Helps prevent "WALWrite" bottlenecks during your UPDATE test
# wal_level = logical             # Good for modern tools
# checkpoint_timeout = 15min
# max_wal_size = 1GB
# min_wal_size = 80MB